kind: Pod
apiVersion: v1
metadata:
  name: test-persistent
spec:
  containers:
    - name: app
      image: alpine
      volumeMounts:
      - name: data
        mountPath: /var/nfs # Please change the destination you like the share to be mounted too
      command: ["/bin/sh"]
      args: ["-c", "while true; do date >> /var/nfs/dates.txt; sleep 5; done"]
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: pvc-test
