apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  capacity:
    storage: 30Gi # This size is used to match a volume to a tenents claim
  accessModes:
    - ReadWriteMany # Access modes are defined below
  nfs:
    server: xx.xx.xx.xx # Please change this to your NFS server
    path: /mnt/folder-nfs # Please change this to the relevant share
