apiVersion: v1
kind: Namespace
metadata:
  name: svc-master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapp-deployment
  namespace: svc-master
  labels:
    app: dotnetapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dotnetapp
  template:
    metadata:
      labels:
        app: dotnetapp
    spec:
      containers:
      - name: dotnetapp
        image: nnorman062/sample:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnetapp
  namespace: svc-master
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: dotnetapp
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: dotnet-ingress
  namespace: svc-master
spec:
  rules:
  - host: "test-dotnet.nnorman.tech"
    http:
      paths:
      - backend:
          serviceName: dotnetapp
          servicePort: 80
