apiVersion: v1
kind: Pod
metadata:
  name: gluster-pod
  labels:
    name: gluster-pod  
spec:
  containers:
  - name: gluster-pod
    image: busybox       
    command: ["sleep", "60000"]
    volumeMounts:
    - name: gluster-vol
      mountPath: /usr/share/busybox 
      readOnly: false
    securityContext:
      privileged: true
  securityContext:
    supplementalGroups: [590]       
  volumes:
  - name: gluster-vol   
    persistentVolumeClaim:
      claimName: gluster-pvc2
