apiVersion: v1
kind: Pod
metadata:
  name: gluster-apache-pod
  labels:
    name: gluster-apache-pod  
spec:
  containers:
  - name: gluster-apache-pod
    image: httpd:2.4       
    volumeMounts:
    - name: gluster-vol2
      mountPath: /var/www/html 
      readOnly: false
  volumes:
  - name: gluster-vol2   
    persistentVolumeClaim:
      claimName: gluster-pvc
