apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: gluster-pvc3
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-heketi-external
spec:
 accessModes:
  - ReadOnlyMany
 resources:
   requests:
     storage: 100M
