apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: gluster-pvc2
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-heketi-external
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 1Gi
